### PR TITLE
Pull request using-bootstrap project

### PR DESCRIPTION
**Pull request by javitocor**
In this project, I have cloned the Newsweek newspaper website (https://www.newsweek.com/) using HTML, CSS and Bootstrap.
With HTML I give structure to the page. I have used bootstrap and its classes to layout the page and CSS for smaller details and for the media queries.
I have added two breakpoints at 992px and 768px.
I fixed all the sticklers and the validation webpage https://validator.w3.org/ gave me no errors.

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi @javitocor, you have really done a great job. 👍 Congratulations. However, we need to make a few changes to get the project approved. Find comment below:
- ```Laptop mode``` we need to fix the horizontal scroll
hor
- ```Tablet mode``` we need to fix the positioning of the social icons. Currently, it looks this way
soc
```Original```
soco
- ```Mobile mode``` Currently, the nav needs some fixing. It needs to take the full width, sign in and subscribe breaks. Check it out
mnav
```Original version```
mnav1
- Consider increasing the width of the top story section. Currently, it looks like this
top
```Original version```
top1
- ```In More Stories``` the images stretch and the image should take 60% of the width while text takes 40%. Currently,  it looks like this 
mor
```Original version```
mor1
- Consider the order of positioning. ```Culture and travel``` comes after ```More stories```
- Let us add padding to the opinion section to give space between the image and text. Currently, it looks like this
op1
```Original version```
op2
- ```In latest news section``` let give the width of the image 60% and text 40%. Currently, it looks this way
ln1
```Original version```
ln2
- ```In the magazine``` has only 1 column on a mobile device. But currently, it has three columns
itm1
```Original version```
itm
- Currently, the social icon in the footer breaks
sfi
```Original version```
sfi1
[OPTIONAL]
- Currently, above the subscribe looks like this. We can give the image width of 60% and text width of 40%
LW
```Original version```
LW1


Kindly make these changes and submit another code review. 👍 
Good luck with your next submission 🙂 
Happy coding 💻 
Daniel Larbi Addo

**Comment by javitocor** [comment]
I have taken note of the latest review and fix all the problems

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this under 15 minutes for your full review :ok_hand:

**Comment by nikasulo** [comment]
# Really solid work @javitocor ! :medal_military: 
You have done a fantastic job and your UI is looking great. Your navigation bar is the neatest and most responsive one I have come across :1st_place_medal: . Please consider my comments below and examing the screenshots I have attached

#### Responsiveness
You have put a lot of work into this requirement, however, there are a few more bugs left to squash. Please consider the following screenshots of key sections where I came across issues.

* Newsletter and Subscribe
Please consider the sections highlighted below at 768px and above, comparing closely with the original site, you may notice differences in size, padding, and image responsiveness. Please consider the social media icons in the footer as well as they may not be properly aligned.
screenshot
screenshot

* In The Magazine
This section also has some issues with the image responsiveness and sizing of elements on the tablet screen sizes (> 767px). Please consider the following screenshots from your project and compare this section with that on  the original site.
screenshot
screenshot

* Top Story
Considering the following sections, you may find that the width of the right half is not as it should be and as such it is affecting the section as a whole negatively. Please consider giving this a second look :+1: 
screenshot

### Summary
Please consider the sections highlighted above, in the top story section, the width of the right half is a little less than it should be, the "In The Magazine section" could use a thorough look at image responsiveness and the same goes for the subscribe and newsletter sections. Please make these changes and request another review :100: I wish you all the best and see you at the top :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by javitocor** [comment]
-Changed subscribe pictures size
-Changed top stories and featured articles sections size
- The social media icons and the magazine aside photo looks fine in my browsers (Mozilla, chrome and iexplorer)

**Review by rOluochKe — APPROVED** [review]
Hello Team!
### Congratulations :clap: :boom: Your project has been approved.
### You can merge and submit a project completion form from your dashboard.

**Pull request merged**
